version: "3.4"

services:
    inno_be:
        image: inno_be
        build:
            context: .
            dockerfile: ./Dockerfile
        # environment:
        #   NODE_ENV: production
        ports:
            - 8080:8080

    geth:
        image: ethereum/client-go
        ports:
            - 8545:8545
            - 8546:8546
        volumes:
            # path:path => first path is the local path, second path is the path in the container
            - ./geth:/root/.ethereum
            - ./data:/root/ # TODO: remove this line

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongo:/data/db
